
GET https://fullstackopenpart3render.onrender.com/api/persons

###

DELETE http://localhost:3001/api/persons/100

###
POST https://fullstackopenpart3render.onrender.com/api/persons
content-type: application/json

{
    "name": "bbc",
    "number": "123"
}