
GET http://localhost:3001/api/people

###

DELETE http://localhost:3001/api/people/100

###
POST http://localhost:3001/api/people
content-type: application/json

{
    "name": "bbc",
    "number": "123"
}